version: '3.8'
services:
  auth:
    build: .
    command: gunicorn auth_service.wsgi:app -b 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=auth_service
      - FLASK_ENV=production
    volumes:
      - ./auth_service:/app/auth_service

  web:
    build: .
    command: gunicorn frontend_service.wsgi:app -b 0.0.0.0:8001
    ports:
      - "8001:8001"
    environment:
      - FLASK_APP=frontend_service
      - FLASK_ENV=production
      - AUTH_SERVICE_URL=http://auth:8000
    volumes:
      - ./frontend_service:/app/frontend_service
    depends_on:
      - auth
