version: '3'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    volumes:
      - ./auth-service:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    command: python run.py

  frontend-service:
    build: ./frontend-service
    ports:
      - "5001:5001"
    volumes:
      - ./frontend-service:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - AUTH_SERVICE_URL=http://auth-service:5000
    depends_on:
      - auth-service
    command: python run.py
