name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "auth-service/**,frontend-service/**,static/**,*.py,*.md,*.yml,.htaccess"
          target: "${{ secrets.DEPLOY_PATH }}"
          rm: true
          strip_components: 0
          overwrite: true

      - name: Set permissions and install dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            chmod -R 755 ${{ secrets.DEPLOY_PATH }}
            find ${{ secrets.DEPLOY_PATH }} -type f -exec chmod 644 {} \;
            chmod +x ${{ secrets.DEPLOY_PATH }}/index.py
            chmod +x ${{ secrets.DEPLOY_PATH }}/frontend-service/app.py
            cd ${{ secrets.DEPLOY_PATH }}
            curl https://bootstrap.pypa.io/pip/3.6/get-pip.py -o get-pip.py
            python3 get-pip.py --target=${{ secrets.DEPLOY_PATH }}/lib
            ${{ secrets.DEPLOY_PATH }}/lib/bin/pip install --target=${{ secrets.DEPLOY_PATH }}/lib -r requirements.txt
            rm get-pip.py
            echo "${{ secrets.DEPLOY_PATH }}/lib" > ${{ secrets.DEPLOY_PATH }}/.pth
            chmod 644 ${{ secrets.DEPLOY_PATH }}/.pth
