name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: |
            auth-service/
            frontend-service/
            *.py
            *.md
            *.yml
            !.git/
            !.github/
            !docker-compose*.yml
            !test_*.py
            !run_*.sh
          target: "${{ secrets.DEPLOY_PATH }}"
          rm: true
          strip_components: 0
