name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: python:3.6-slim
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          mkdir -p lib
          pip install --target=lib -r requirements.txt

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "auth-service/**,frontend-service/**,static/**,lib/**,*.py,*.md,*.yml,.htaccess"
          target: "${{ secrets.DEPLOY_PATH }}"
          rm: true
          strip_components: 0
          overwrite: true

      - name: Set permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            chmod -R 755 ${{ secrets.DEPLOY_PATH }}
            find ${{ secrets.DEPLOY_PATH }} -type f -exec chmod 644 {} \;
            chmod +x ${{ secrets.DEPLOY_PATH }}/index.py
            chmod +x ${{ secrets.DEPLOY_PATH }}/frontend-service/app.py
