name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.2'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest test_services.py -v
        
    - name: Check code style
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    container: python:3.13.2-slim
    
    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y curl

    - name: Install Python dependencies
      run: |
        mkdir -p lib
        pip install --target=lib -r requirements.txt

    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "auth_service/**,frontend_service/**,static/**,lib/**,*.py,*.md,*.yml,.htaccess,deploy.sh"
        target: "${{ secrets.DEPLOY_PATH }}"
        rm: true
        strip_components: 0
        overwrite: true

    - name: Set permissions
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # Asegurar permisos de directorios
          find ${{ secrets.DEPLOY_PATH }} -type d -exec chmod 755 {} \;
          
          # Asegurar permisos de archivos
          find ${{ secrets.DEPLOY_PATH }} -type f -exec chmod 644 {} \;
          
          # Permisos especiales para ejecutables
          chmod 755 ${{ secrets.DEPLOY_PATH }}/index.py
          chmod 755 ${{ secrets.DEPLOY_PATH }}/deploy.sh
          chmod 755 ${{ secrets.DEPLOY_PATH }}/wsgi.py
          chmod 755 ${{ secrets.DEPLOY_PATH }}/frontend_service/wsgi.py
          chmod 755 ${{ secrets.DEPLOY_PATH }}/auth_service/wsgi.py
          
          # Permisos para directorios de cache y logs
          mkdir -p ${{ secrets.DEPLOY_PATH }}/logs
          mkdir -p ${{ secrets.DEPLOY_PATH }}/cache
          chmod -R 777 ${{ secrets.DEPLOY_PATH }}/logs
          chmod -R 777 ${{ secrets.DEPLOY_PATH }}/cache

    - name: Execute deploy script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ secrets.DEPLOY_PATH }}
          chmod +x deploy.sh
          ./deploy.sh 